[package]
name = "xtable-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "xtctl"
path = "src/main.rs"

[dependencies]
xtable-core = { path = "../xtable-core" }

tokio = { workspace = true }
clap = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
ulid = { workspace = true }
aws-sdk-s3 = { workspace = true }
aws-config = { workspace = true }
aws-credential-types = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
futures = { workspace = true }
hmac = "0.12"
aws-sigv4 = "1.2"
http = "1.1"
chrono = { workspace = true }
aws-smithy-runtime-api = { workspace = true }