[package]
name = "xtable-auth"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
xtable-core = { path = "../xtable-core" }

s3s = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
async-trait = { workspace = true }
axum = { workspace = true }
hyper = { workspace = true }
http = "1.1"
sha2 = { workspace = true }
hmac = "0.12"
hex = "0.4"